version: 2.1

commands:
  build-common:
    parameters:
      hadoop_version:
        # hadoop2 or hadoop3
        type: string
    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Revert to traditional pip install when build refactored, in the meantime:
      - run:
          name: Install build tools
          command: |
            sudo apt-get update -y
            DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true TZ=UTC sudo apt-get install -y --no-install-recommends openjdk-8-jdk maven
            
      - run:
          name: Build
          command: |
            mvn clean verify -Pspark-3.0 -Pspark-scala-2.12 -DskipTests

jobs:
  build-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

    working_directory: ~/zeppelin

    steps:
      - build-common:
          hadoop_version: "hadoop3"

workflows:
  version: 2
  run-build-and-tests:
    jobs:
      - build-arm64
